* Wisdom

A wise way to manage Emacs configurations using Org.

** Quickstart

A minimal `init.el` setup. This is the only "pure" Emacs Lisp code
that is required to get up and running.

#+BEGIN_SRC emacs-lisp

;; Install use-package and straight

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
        "straight/repos/straight.el/bootstrap.el"
        (or (bound-and-true-p straight-base-dir)
            user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; Use latest version of Org instead of Emacs' built-in version.

(straight-use-package 'org)

;; Install Wisdom, compile and load org files in your desired
;; locations.

(use-package wisdom
  :straight (wisdom :type git :host github :repo "kwrooijen/wisdom")
  :custom
  (wisdom-org-directory "~/.emacs.d/org")
  (wisdom-output-directory "~/.emacs.d/wisdom")
  :config
  (wisdom-compile-directory)
  (wisdom-load-directory))
#+END_SRC


** Intro

Wisdom


** Org file options

By default, Wisdom enables lexical binding for better variable scope
management. To disable this feature, you can set the `LEXICAL_BINDING`
option to `nil`.

#+BEGIN_SRC org
#+LEXICAL_BINDING: nil
#+END_SRC

Wisdom loads Org files based on their priority levels. By default, all
files have a priority level of 10; the lower the number, the higher
the priority and the earlier it will be loaded.

#+BEGIN_SRC org
#+PRIORITY: 2
#+END_SRC

Pull a remote Org config file into your own Org file. This allows
using other people's configurations and setups. After you've added a
remote Org file you can add "finishing touches" in that same file.

#+BEGIN_SRC org
#+REMOTE: (:host github :repo kwrooijen/test-org :branch master :file key-chord.org)
#+END_SRC
